"""
Django settings for dcblog project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4=^y3kp=6245_4%gtfzfzqwfnw6wqwqeweqw4_dmarbffsnzxm^%#ixow'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'article',
    'tag',
    'author',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'dcblog.context_processors.site_info',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dcblog',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost'
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

DCBLOG_CONFIG = {
    'SITE_NAME': os.getenv('SITE_NAME', "瓦都尅'Blog"),
    'SITE_AUTHOR': os.getenv('SITE_AUTHOR', "瓦都尅"),
    'SITE_DESCRIPTION': os.getenv('SITE_DESCRIPTION', '渗透测试 | 应急响应 | 安全开发 | 一个人的安全部'),
    'SITE_HOME_BACKGROUND': os.getenv('SITE_HOME_BACKGROUND', '/static/img/home-bg.png'),
    'SITE_ARTICLE_BACKGROUND': os.getenv('SITE_POST_BACKGROUND', '/static/img/article-bg.png'),
    'SITE_FORM_BACKGROUND': os.getenv('SITE_FORM_BACKGROUND', '/static/img/form-bg.png'),
    'SITE_ERROR_BACKGROUND': os.getenv('SITE_ERROR_BACKGROUND', '/static/img/error-bg.png'),
    'SITE_ABOUT_BACKGROUND': os.getenv('SITE_ABOUT_BACKGROUND', '/static/img/about.png'),
    'SITE_TAG_BACKGROUND': os.getenv('SITE_TAG_BACKGROUND', '/static/img/tag.png'),
    'SITE_ZHIHU_URL': os.getenv('ZHIHU_URL', 'https://www.zhihu.com/'),
    'SITE_GITHUB_URL': os.getenv('GITHUB_URL', 'https://github.com/w2n1ck')
}
